name: CD

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PI_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: smartthingspi
          GIT_AUTHOR_EMAIL: pi-team@smartthings.com
          GIT_COMMITTER_NAME: smartthingspi
          GIT_COMMITTER_EMAIL: pi-team@smartthings.com
        run: npx semantic-release
