name: CD

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

jobs:
  release:
    # don't run on forks
    if: github.repository_owner == 'SmartThingsCommunity'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PI_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: smartthingspi
          GIT_AUTHOR_EMAIL: pi-team@smartthings.com
          GIT_COMMITTER_NAME: smartthingspi
          GIT_COMMITTER_EMAIL: pi-team@smartthings.com
        run: npx semantic-release
