name: CI/CD

on:
  push:
  pull_request:
  workflow_dispatch:
    branches:
      - main

jobs:
  lint-commits:
    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci --ignore-scripts
      - run: npx commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # add/remove versions as we move support forward
        node-version: [14, 16, 18]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npm test

  release:
    needs: build

    # don't run on forks
    if: ${{ github.repository_owner == 'SmartThingsCommunity' && github.ref == 'refs/heads/main' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run version
          publish: npm run release
          commit: "chore(changesets): version packages"
          title: "chore(changesets): version packages"
          createGithubReleases: true
        env:
          # We can't use the built-in GITHUB_TOKEN for releases, at least for now.
          # https://github.com/github-community/community/discussions/13836
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
