name: commitlint

on: [pull_request]

jobs:
  lint-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci --ignore-scripts
      - run: npx commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD
